app/routes/post.py
from flask import Blueprint, render_template, request, redirect, abort, flash, url_for
from flask_login import login_required, current_user

from ..forms import TeacherForm
from ..models.user import User
from ..extensions import db
from ..models.post import Post

post = Blueprint('post', __name__)

@post.route('/')
def all():
    return render_template('post/head.html')

@post.route('/post')
def posters():
    form = TeacherForm()
    form.teacher.choices = [t.name for t in User.query.filter_by(status='teacher')]

    if request.method == "POST":
        teacher = request.form.get('teacher')
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods=['POST', 'GET'])
@login_required
def create():
    if request.method == 'POST':
        topic = request.form.get('topic')
        maximum = request.form.get('maximum')
        actions = request.form.get('actions')
        dignits = request.form.get('dignits')

        post = Post(teacher=current_user.id, topic=topic, maximum=maximum, actions=actions, dignits=dignits)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/post')
        except Exception as e:
            print(str(e))
    else:
        pass
    return render_template('post/create.html')

# @post.route('/post/<int:id>/update', methods=['POST', 'GET'])
# @login_required
# def update(id):
#     post = Post.query.get(id)
#     if request.method == 'POST':
#         post.teacher = request.form['teacher']
#         post.subject = request.form['subject']
#         post.student = request.form['student']
#
#         try:
#             db.session.commit()
#             return redirect('/')
#         except Exception as e:
#             print(str(e))
#     else:
#         return render_template('post/update.html', post=post)

@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
@login_required
def delete(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect('/post')
        except Exception as e:
            print(str(e))
            return (str(e))
    else:
        abort(403)



@post.route('/post/<string:random_hex>/show_queue', methods=['GET'])
@login_required
def show_queue(random_hex):
    post = Post.query.filter_by(random_hex=random_hex).first_or_404()
    return render_template('post/show_queue.html', post=post)


@post.route('/post/<string:random_hex>/submit_answer', methods=['GET', 'POST'])
@login_required
def submit_answer(random_hex):
    # Находим пост по уникальному идентификатору random_hex
    post = Post.query.filter_by(random_hex=random_hex).first_or_404()

    if request.method == 'POST':
        # Получаем ответ пользователя
        user_response = request.form.get('response')

        # Проверяем правильность ответа
        if user_response == post.res:
            flash('Да! Молодец! Правильный ответ!', 'success')
            return redirect(url_for('post.posters'))  # Перенаправляем на главную страницу
        else:
            flash('Ошибка! Попробуйте снова.', 'danger')
            return render_template('post/submit_answer.html', post=post, show_retry=True)

    return render_template('post/submit_answer.html', post=post)

@post.route('/random_hex_input', methods=['GET', 'POST'])
def handle_random_hex():
    if request.method == 'POST':
        random_hex = request.form.get('random_hex')

        if not random_hex:
            flash('Please enter a random hex.')
            return render_template('post/random_hex_input.html')

        # Поиск записи в базе данных
        post = Post.query.filter_by(random_hex=random_hex).first()

        if post:
            return redirect(url_for('post.show_queue', random_hex=random_hex))
        else:
            flash('Invalid random hex. Please try again.')
            return render_template('post/random_hex_input.html')

    return render_template('post/random_hex_input.html')

app/routes/user.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user

from ..functions import save_picture, check_ava
from ..forms import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User

user = Blueprint('user', __name__)


@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Получаем статус из скрытого поля формы
        status = request.form.get('status', 'student')  # По умолчанию 'student'

        existing_user = User.query.filter_by(login=form.login.data).first()
        if existing_user:
            flash(f"Логин {form.login.data} уже занят. Пожалуйста, выберите другой логин.", "danger")
            return redirect(url_for('user.register'))

        # Хешируем пароль
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        # Сохраняем аватар и проверяем его формат
        avatar_filename = save_picture(form.avatar.data)
        if check_ava(avatar_filename) == 0:
            flash(
                "Выбран неверный формат аватара. Доступные форматы PNG, JPEG, JPG. Пожалуйста, выберите другой аватар.",
                "danger")
            return redirect(url_for('user.register'))

        # Создаем нового пользователя
        user = User(name=form.name.data, login=form.login.data, avatar=avatar_filename, password=hashed_password,
                    status=status)

        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Поздравляем, {form.login.data}! Вы успешно зарегистрированы.", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            print(str(e))
            flash("При регистрации произошла ошибка. Пожалуйста, попробуйте еще раз.", "danger")
            return redirect(url_for('user.register'))

    # Если форма не прошла валидацию
    for field, errors in form.errors.items():
        for error in errors:
            flash(f"Ошибка в поле {getattr(form, field).label.text}: {error}", "danger")

    return render_template('user/register.html', form=form)


@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Поздравляем, {form.login.data}! Вы успешно авторизованы", "success")
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash(f"Ошибка входа. Пожалуйста проверьте логин и пароль!", "danger")
    return render_template('user/login.html', form=form)

@user.route('/user/logout')
def logout():
    logout_user()
    return redirect('/')

app/templates/main/_flash.html
<!-- FLASH MESSAGES -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<!-- FLASH MESSAGES -->

app/templates/main/_footer.html
{% block style %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css">
{% endblock %}

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a href="https://www.instagram.com/maxium_gomel?igsh=MWNkZ3RoOG5tb2Fwag=="><i class="bi bi-instagram"></i></a></li>
      <!--  <li class="ms-3"><a href="#"><i class="bi bi-twitter"></i></a></li>
        <li class="ms-3"><a href="#"><i class="bi bi-facebook"></i></a></li>-->
    </ul>
  </footer>
</div>

app/templates/main/_header.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{{ url_for('post.all')}}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <img class="header__img" src="{{ url_for('static', filename='img/logo.png')}}", alt="logo">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{ url_for('post.all')}}" class="nav-link px-2 text-secondary">Главная</a></li>
        </ul>


        <div class="text-end">
        {% if current_user.is_authenticated %}
            <span>Добро пожаловать, {{ current_user.login }}</span>
            <a href="{{ url_for('user.logout') }}" class="btn btn-outline-light me-2">Выйти</a>
        {% else %}
            <a href="{{ url_for('user.login') }}" class="btn btn-outline-light me-2">Войти</a>
            <a href="{{ url_for('user.register') }}" class="btn btn-warning">Регистрация</a>
        {% endif %}
        </div>
      </div>
    </div>
  </header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% block extra_styles %}{% endblock %}
</head>
<body>
<header class="header">{% include 'main/_header.html' %}</header>
<div class="page">
    <main class="content">
        {% include 'main/_flash.html' %}
        <h1>{{ self.title() }}</h1>
        {% block content %}{% endblock %}
    </main>
    <footer class="py-3 my-4">{% include 'main/_footer.html' %}</footer>
</div>
    <script scr="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script scr="{{ url_for('static', filename='js/libs/bootstrap.bundle.min.js') }}"></script>
    <script scr="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>