app/models/post.py
from datetime import datetime
import os
import binascii
from ..extensions import db
from ..functions import generate_queue_def, generate_queue_bro

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    topic = db.Column(db.String(250))
    maximum = db.Column(db.Integer)
    actions = db.Column(db.Integer)
    dignits = db.Column(db.Integer)
    queue = db.Column(db.Text)
    res = db.Column(db.Text)
    random_hex = db.Column(db.String(64), unique=True, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)

    def __init__(self, teacher, topic, maximum, actions, dignits):
        self.teacher = teacher
        self.topic = topic
        self.maximum = maximum
        self.actions = actions
        self.dignits = dignits

        # Генерация queue и res при создании постера
        if topic == 'просто':
            self.queue, self.res, self.random_hex = generate_queue_def(int(actions), int(maximum), int(dignits))
        elif topic == 'брат':
            self.queue, self.res, self.random_hex = generate_queue_bro(int(actions), 9, int(dignits), int(maximum))

app/routes/flas.py
import random

from flask import Blueprint, render_template, request, redirect, abort, flash, url_for, session
from flask_login import login_required, current_user

from ..extensions import db

flast = Blueprint('flast', __name__)

# Глобальные переменные для хранения диапазона
lower_bound = 1
upper_bound = 100


@flast.route('/flas', methods=['GET'])
@login_required
def flas():
    return render_template('flast/flas.html')



@flast.route('/flas/task1', methods=['GET', 'POST'])
@login_required
def task1():
    random_number = session.get('random_number', None)

    if random_number is None:
        # Генерация случайного числа в диапазоне 1-9
        random_number = random.randint(1, 9)
        session['random_number'] = random_number

    # Преобразуем число в строку и разбиваем на отдельные цифры
    number_str = str(random_number)
    number_images = [f'{digit}.png' for digit in number_str]

    if request.method == 'POST':
        action = request.form.get('action')

        if action == 'check':
            user_input = request.form.get('user_input')
            if user_input == number_str:
                flash('Вы правильно ввели число!', 'success')
                random_number = random.randint(1, 9)
                session['random_number'] = random_number
                return redirect(url_for('flast.task1'))
            else:
                flash('Неправильный ответ, попробуйте снова.', 'danger')

        elif action == 'next':
            random_number = random.randint(1, 9)
            session['random_number'] = random_number
            return redirect(url_for('flast.task1'))

    return render_template('flast/task1.html', number_images=number_images)

@flast.route('/flas/task2', methods=['GET', 'POST'])
@login_required
def task2():
    random_number = session.get('random_number', None)

    if random_number is None:
        random_number = random.randint(10, 99)
        session['random_number'] = random_number

    number_str = str(random_number)
    number_images = [f'{digit}.png' for digit in number_str]

    if request.method == 'POST':
        action = request.form.get('action')

        if action == 'check':
            user_input = request.form.get('user_input')
            if user_input == number_str:
                flash('Вы правильно ввели число!', 'success')
                random_number = random.randint(10, 99)
                session['random_number'] = random_number
                return redirect(url_for('flast.task2'))
            else:
                flash('Неправильный ответ, попробуйте снова.', 'danger')

        elif action == 'next':
            random_number = random.randint(10, 99)
            session['random_number'] = random_number
            return redirect(url_for('flast.task2'))

    return render_template('flast/task2.html', number_images=number_images)

@flast.route('/flas/task3', methods=['GET', 'POST'])
@login_required
def task3():
    random_number = session.get('random_number', None)

    if random_number is None:
        random_number = random.randint(100, 999)
        session['random_number'] = random_number

    number_str = str(random_number)
    number_images = [f'{digit}.png' for digit in number_str]

    if request.method == 'POST':
        action = request.form.get('action')

        if action == 'check':
            user_input = request.form.get('user_input')
            if user_input == number_str:
                flash('Вы правильно ввели число!', 'success')
                random_number = random.randint(100, 999)
                session['random_number'] = random_number
                return redirect(url_for('flast.task3'))
            else:
                flash('Неправильный ответ, попробуйте снова.', 'danger')

        elif action == 'next':
            random_number = random.randint(100, 999)
            session['random_number'] = random_number
            return redirect(url_for('flast.task3'))

    return render_template('flast/task3.html', number_images=number_images)


app/routes/post.py
from flask import Blueprint, render_template, request, redirect, abort, flash, url_for
from flask_login import login_required, current_user

from ..forms import TeacherForm
from ..models.user import User
from ..extensions import db
from ..models.post import Post

post = Blueprint('post', __name__)

@post.route('/')
def all():
    return render_template('post/head.html')

@post.route('/post')
def posters():
    form = TeacherForm()
    form.teacher.choices = [t.name for t in User.query.filter_by(status='teacher')]

    if request.method == "POST":
        teacher = request.form.get('teacher')
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods=['POST', 'GET'])
@login_required
def create():
    if request.method == 'POST':
        topic = request.form.get('topic')
        maximum = request.form.get('maximum')
        actions = request.form.get('actions')
        dignits = request.form.get('dignits')

        post = Post(teacher=current_user.id, topic=topic, maximum=maximum, actions=actions, dignits=dignits)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/post')
        except Exception as e:
            print(str(e))
    else:
        pass
    return render_template('post/create.html')

# @post.route('/post/<int:id>/update', methods=['POST', 'GET'])
# @login_required
# def update(id):
#     post = Post.query.get(id)
#     if request.method == 'POST':
#         post.teacher = request.form['teacher']
#         post.subject = request.form['subject']
#         post.student = request.form['student']
#
#         try:
#             db.session.commit()
#             return redirect('/')
#         except Exception as e:
#             print(str(e))
#     else:
#         return render_template('post/update.html', post=post)

@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
@login_required
def delete(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect('/post')
        except Exception as e:
            print(str(e))
            return (str(e))
    else:
        abort(403)



@post.route('/post/<string:random_hex>/show_queue', methods=['GET'])
@login_required
def show_queue(random_hex):
    post = Post.query.filter_by(random_hex=random_hex).first_or_404()
    return render_template('post/show_queue.html', post=post)


@post.route('/post/<string:random_hex>/submit_answer', methods=['GET', 'POST'])
@login_required
def submit_answer(random_hex):
    # Находим пост по уникальному идентификатору random_hex
    post = Post.query.filter_by(random_hex=random_hex).first_or_404()

    if request.method == 'POST':
        # Получаем ответ пользователя
        user_response = request.form.get('response')

        # Проверяем правильность ответа
        if user_response == post.res:
            flash('Да! Молодец! Правильный ответ!', 'success')
            return redirect(url_for('post.posters'))  # Перенаправляем на главную страницу
        else:
            flash('Ошибка! Попробуйте снова.', 'danger')
            return render_template('post/submit_answer.html', post=post, show_retry=True)

    return render_template('post/submit_answer.html', post=post)

@post.route('/random_hex_input', methods=['GET', 'POST'])
def handle_random_hex():
    if request.method == 'POST':
        random_hex = request.form.get('random_hex')

        if not random_hex:
            flash('Please enter a random hex.')
            return render_template('post/random_hex_input.html')

        # Поиск записи в базе данных
        post = Post.query.filter_by(random_hex=random_hex).first()

        if post:
            return redirect(url_for('post.show_queue', random_hex=random_hex))
        else:
            flash('Invalid random hex. Please try again.')
            return render_template('post/random_hex_input.html')

    return render_template('post/random_hex_input.html')

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %}Режимы{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
  <style>
    /* Стиль для кнопки по центру */
    .centered-button {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      margin-bottom: 20px;
    }

    .centered-button a {
      padding: 10px 20px;
      font-size: 16px;
      text-decoration: none;
      background-color: #28a745;
      color: white;
      border-radius: 5px;
    }

    .centered-button a:hover {
      background-color: #218838;
    }
  </style>
{% endblock %}

{% block content %}

<form method="post" class="form-control d-flex flex-row gap-2" id="teacherForm">
  {{ form.csrf_token }}
  {{ form.teacher }}
  <input type="submit" class="btn btn-success" value="Показать">
</form>



<!-- Центрируем кнопку под таблицей -->
<div class="centered-button">
  <a href="{{ url_for('post.create') }}">Создание очереди</a>
</div>
<div class="table-responsive custom-table-responsive">
  <table class="table custom-table">
    <thead>
      <tr>
        <th scope="col">Создатель</th>
        <th scope="col">Тема</th>
        <th scope="col"></th>
        <th scope="col">Тег</th>
        <th scope="col">Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr scope="row">
        <td>{{ post.author.name }}</td>
        <td>{{ post.topic }}</td>
        <td>{{ post.maximum }}</td>
        <td>{{ post.random_hex }}</td>
          <td>
          <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
          <a href="{{ url_for('post.show_queue', random_hex=post.random_hex) }}" class="btn btn-sm btn-secondary"><span class="fa fa-angle-right"></span></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}Создание режима{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/btns.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="teacher" type="text" value="{{ current_user.name }}" class="form-control" readonly>

    <!-- Выпадающий список для выбора темы -->
    <select name="topic" id="topic" class="form-control" onchange="updateMaximumRange()">
        <option value="просто">Просто</option>
        <option value="брат">Брат</option>
    </select>

    <!-- Ползунок для выбора максимума -->
    <label for="maximum" class="form-label">Выберите максимум:</label>
    <input name="maximum" id="maximum" type="range" class="form-range" min="1" max="9" value="2" oninput="updateMaximumValue()">
    <span id="maximumValue">2</span>

    <!-- Ползунок для выбора действий -->
    <label for="actions" class="form-label">Выберите количество действий:</label>
    <input name="actions" id="actions" type="range" class="form-range" min="2" max="20" value="2" oninput="updateActionValue()">
    <span id="actionValue">2</span>

    <!-- Toggle-кнопки для выбора dignits -->
    <label class="form-label">Выберите число (1-3):</label>
    <div class="toggle-container">
        <button type="button" class="toggle-button active" data-value="1">1</button>
        <button type="button" class="toggle-button" data-value="2">2</button>
        <button type="button" class="toggle-button" data-value="3">3</button>
        <!-- <button type="button" class="toggle-button" data-value="4">4</button> -->
        <input type="hidden" name="dignits" id="dignits" value="1"> <!-- Скрытое поле для отправки -->
    </div>

    <input value="Добавить" type="submit" class="btn btn-success">
</form>

<script>
    // Функции для обновления диапазонов значений ползунков
    function updateMaximumRange() {
        var topic = document.getElementById("topic").value;
        var maximumSlider = document.getElementById("maximum");

        if (topic === "просто") {
            maximumSlider.min = 2;
            maximumSlider.max = 9;
            maximumSlider.value = 2;
        } else if (topic === "брат") {
            maximumSlider.min = 1;
            maximumSlider.max = 4;
            maximumSlider.value = 1;
        }
        updateMaximumValue();  // Обновляем отображаемое значение
    }

    function updateMaximumValue() {
        var maximumValue = document.getElementById("maximum").value;
        document.getElementById("maximumValue").innerText = maximumValue;
    }

    function updateActionValue() {
        var actionValue = document.getElementById("actions").value;
        document.getElementById("actionValue").innerText = actionValue;
    }

    // Логика работы с toggle-кнопками
    const toggleButtons = document.querySelectorAll('.toggle-button');
    const dignitsInput = document.getElementById('dignits');

    toggleButtons.forEach(button => {
        button.addEventListener('click', function() {
            // Снять активный класс со всех кнопок
            toggleButtons.forEach(btn => btn.classList.remove('active'));
            // Добавить активный класс на текущую кнопку
            this.classList.add('active');
            // Обновить скрытое поле с выбранным значением
            dignitsInput.value = this.getAttribute('data-value');
        });
    });

    // Инициализация значений при загрузке страницы
    window.onload = function() {
        updateMaximumRange();
        updateActionValue();
    };
</script>
{% endblock %}

app/templates/post/head.html
{% extends 'main/base.html' %}

{% block style %}
  <style>
    .center-buttons {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 80vh; /* Центрируем по высоте */
      flex-direction: row;
    }

    .center-buttons .btn {
      width: 200px;
      height: 150px;
      font-size: 20px;
      margin: 10px;
    }
  </style>
{% endblock %}

{% block content %}
<div class="center-buttons">
    <a href="{{ url_for('post.posters') }}" class="btn btn-outline-light me-2">Режимы</a>
    <a href="{{ url_for('flast.flas') }}" class="btn btn-outline-light me-2">Флеш-карты</a>
    <a href="{{ url_for('post.handle_random_hex') }}" class="btn btn-outline-light me-2">Домашнее задание</a>
</div>
{% endblock %}

app/templates/post/random_hex_input.html
{% extends 'main/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <form method="POST" action="{{ url_for('post.handle_random_hex') }}">
        <div>
            <label for="random_hex">Enter Random Hex:</label>
            <input type="text" id="random_hex" name="random_hex" placeholder="Enter code">
        </div>
        <div style="margin-top: 10px;">
            <button type="submit">Play</button>
        </div>
    </form>

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
</div>
{% endblock %}

app/templates/post/show_queue.html
{% extends 'main/base.html' %}

{% block style %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/start.css') }}">
{% endblock %}


{% block content %}
<div class="container text-center">
    <h1 id="status">Приготовьтесь!</h1>
    <h2 id="valueDisplay" class="display-4"></h2>

    <!-- Кнопка "Помощь", которая покажет значения queue -->
    <button id="helpButton" class="btn btn-info d-none" onclick="showQueueModal()">Помощь</button>
    <div id="queueDisplay" class="d-none">{{ post.queue }}</div>
</div>

<div id="overlay"></div>  <!-- Затемнённый фон -->
<div id="queueModal"></div>  <!-- Модальное окно для queue -->

<script>
    const queue = "{{ post.queue[1:-1] }}".split(',').map(item => item.trim());  // Преобразуем queue в массив
    const statusElement = document.getElementById('status');
    const valueDisplay = document.getElementById('valueDisplay');
    const helpButton = document.getElementById('helpButton');
    const queueModal = document.getElementById('queueModal');
    const overlay = document.getElementById('overlay');

    let displayDelay = 1000;
    let speechRate = 10;
    let startSequenceDelay = 300;

    function speak(text) {
        const msg = new SpeechSynthesisUtterance(text);
        msg.rate = speechRate;
        window.speechSynthesis.speak(msg);
    }

    function startSequence() {
        setTimeout(() => { statusElement.innerText = 'На старт'; speak('На старт'); }, startSequenceDelay);
        setTimeout(() => { statusElement.innerText = 'Внимание'; speak('Внимание'); }, startSequenceDelay * 2);
        setTimeout(() => { statusElement.innerText = 'Марш'; speak('Марш'); }, startSequenceDelay * 3);
        setTimeout(() => {
            statusElement.innerText = '';
            displayQueue();
        }, startSequenceDelay * 4);
    }

    function displayQueue() {
        let delay = 0;
        queue.forEach((value, index) => {
            setTimeout(() => {
                valueDisplay.innerText = value;
                speak(value);
            }, delay);
            delay += displayDelay;
        });

        setTimeout(() => {
            valueDisplay.innerText = '';
            statusElement.innerText = 'Введите ответ';
            location.href = "{{ url_for('post.submit_answer', random_hex=post.random_hex) }}";
        }, delay);
    }

    function showQueueModal() {
        overlay.classList.add('active');
        queueModal.classList.add('active');
        queueModal.innerText = queue.join(', ');
        helpButton.classList.add('d-none');
    }

    function hideQueueModal() {
        overlay.classList.remove('active');
        queueModal.classList.remove('active');
        helpButton.classList.remove('d-none');
    }

    window.onload = function() {
        startSequence();
    };

    overlay.addEventListener('click', hideQueueModal);
</script>
{% endblock %}

app/templates/post/submit_answer.html
{% extends 'main/base.html' %}

{% block style %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/start.css') }}">

  <!-- Добавляем стили для модального окна -->
  <style>
    /* Стили для модального окна */
    .modal {
      display: none; /* Окно скрыто по умолчанию */
      position: fixed;
      z-index: 1000;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.4); /* Полупрозрачный фон */
    }

    /* Контент модального окна */
    .modal-content {
      background-color: #fefefe;
      margin: 15% auto;
      padding: 20px;
      border: 1px solid #888;
      width: 80%;
      max-width: 500px;
      text-align: center;
    }

    /* Кнопка закрытия модального окна */
    .close {
      color: #aaa;
      float: right;
      font-size: 28px;
      font-weight: bold;
    }

    .close:hover,
    .close:focus {
      color: black;
      text-decoration: none;
      cursor: pointer;
    }

    /* Блокировка остальных элементов на странице */
    body.modal-open {
      overflow: hidden;
    }
  </style>
{% endblock %}

{% block content %}
<div class="container text-center">

    <h1>Введите ответ</h1>
    <form id="responseForm" method="post" action="{{ url_for('post.submit_answer', random_hex=post.random_hex) }}">
        <input type="text" name="response" class="form-control mb-2" placeholder="Введите ответ" required>
        <button type="submit" class="btn btn-success">Принять ответ</button>
    </form>

    {% if show_retry %}
        <button id="retryButton" class="btn btn-warning mt-3">Повторить</button>
    {% endif %}

    <!-- Кнопка для открытия модального окна -->
    <button id="helpButton" class="btn btn-info mt-3">Помощь</button>

    <!-- Модальное окно -->
    <div id="helpModal" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>
        <h5>Очередь</h5>
        <!-- Здесь будет выведена очередь -->
        <p>{{ post.queue[1:-1] }}</p>
      </div>
    </div>

</div>

<!-- Добавляем JavaScript для работы модального окна -->
<script>
    // Получаем элементы
    var modal = document.getElementById("helpModal");
    var btn = document.getElementById("helpButton");
    var span = document.getElementsByClassName("close")[0];

    // Открытие модального окна при нажатии на кнопку "Помощь"
    btn.onclick = function() {
        modal.style.display = "block";
        document.body.classList.add("modal-open"); // Блокировка прокрутки страницы
    }

    // Закрытие модального окна при нажатии на крестик
    span.onclick = function() {
        modal.style.display = "none";
        document.body.classList.remove("modal-open"); // Разблокировка прокрутки
    }

    // Закрытие модального окна при нажатии на любое место вне окна
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
            document.body.classList.remove("modal-open"); // Разблокировка прокрутки
        }
    }

    // Логика для кнопки "Повторить"
    document.getElementById('retryButton')?.addEventListener('click', () => {
        location.href = "{{ url_for('post.show_queue', random_hex=post.random_hex) }}";
    });
</script>

{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}Редактирование темы {{ post.id }}{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{ post.teacher }}" name="teacher" type="text" placeholder="ФИО Преподавателя" class="form-control">
    <input value="{{ post.subject }}" name="subject" type="text" placeholder="Тема" class="form-control">
    <input value="{{ post.student }}" name="student" type="text" placeholder="ФИО Студента" class="form-control">
    <input value="Обновить" type="submit" class="btn btn-success">
</form>
{% endblock %}